"""Create initial tables

Revision ID: d91aca5b8c9d
Revises: 
Create Date: 2025-07-10 17:34:55.076329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91aca5b8c9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('BIN', sa.String(length=12), nullable=False),
    sa.Column('Company', sa.String(length=255), nullable=False),
    sa.Column('OKED', sa.String(length=50), nullable=True),
    sa.Column('Activity', sa.String(length=255), nullable=True),
    sa.Column('KATO', sa.String(length=50), nullable=True),
    sa.Column('Locality', sa.String(length=100), nullable=True),
    sa.Column('KRP', sa.String(length=50), nullable=True),
    sa.Column('Size', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('tax_payment_2021', sa.Float(), nullable=True),
    sa.Column('tax_payment_2022', sa.Float(), nullable=True),
    sa.Column('tax_payment_2023', sa.Float(), nullable=True),
    sa.Column('tax_payment_2024', sa.Float(), nullable=True),
    sa.Column('tax_payment_2025', sa.Float(), nullable=True),
    sa.Column('degreeofrisk', sa.String(length=100), nullable=True),
    sa.Column('executive', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('BIN')
    )
    op.create_index(op.f('ix_companies_Activity'), 'companies', ['Activity'], unique=False)
    op.create_index(op.f('ix_companies_Company'), 'companies', ['Company'], unique=False)
    op.create_index(op.f('ix_companies_KATO'), 'companies', ['KATO'], unique=False)
    op.create_index(op.f('ix_companies_Locality'), 'companies', ['Locality'], unique=False)
    op.create_index(op.f('ix_companies_OKED'), 'companies', ['OKED'], unique=False)
    op.create_index(op.f('ix_companies_Size'), 'companies', ['Size'], unique=False)
    op.create_index(op.f('ix_companies_location'), 'companies', ['location'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fund_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fund_name', sa.String(length=255), nullable=False),
    sa.Column('fund_description', sa.Text(), nullable=True),
    sa.Column('fund_email', sa.String(length=255), nullable=True),
    sa.Column('conversation_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fund_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_location'), table_name='companies')
    op.drop_index(op.f('ix_companies_Size'), table_name='companies')
    op.drop_index(op.f('ix_companies_OKED'), table_name='companies')
    op.drop_index(op.f('ix_companies_Locality'), table_name='companies')
    op.drop_index(op.f('ix_companies_KATO'), table_name='companies')
    op.drop_index(op.f('ix_companies_Company'), table_name='companies')
    op.drop_index(op.f('ix_companies_Activity'), table_name='companies')
    op.drop_table('companies')
    # In downgrade, drop the website column if it exists
    # ### end Alembic commands ###
